//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CustomerComplaintEntities : DbContext
    {
        public CustomerComplaintEntities()
            : base("name=CustomerComplaintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBrandMaster> tblBrandMasters { get; set; }
        public virtual DbSet<tblComplaintCategoryMaster> tblComplaintCategoryMasters { get; set; }
        public virtual DbSet<tblComplaintTypeMaster> tblComplaintTypeMasters { get; set; }
        public virtual DbSet<tblSubstrateMaster> tblSubstrateMasters { get; set; }
        public virtual DbSet<TblComplaintRequestDtl> TblComplaintRequestDtls { get; set; }
        public virtual DbSet<TblRoleMaster> TblRoleMasters { get; set; }
        public virtual DbSet<tblStatusMaster> tblStatusMasters { get; set; }
        public virtual DbSet<tblApprovalDetail> tblApprovalDetails { get; set; }
        public virtual DbSet<TblComplaintReapplicationSystemInfoDtl> TblComplaintReapplicationSystemInfoDtls { get; set; }
        public virtual DbSet<tblComplaintReappPhotoDtl> tblComplaintReappPhotoDtls { get; set; }
        public virtual DbSet<tblComplaintPlantReprocess> tblComplaintPlantReprocesses { get; set; }
        public virtual DbSet<tblApprovalHeader> tblApprovalHeaders { get; set; }
        public virtual DbSet<tblFutureStatu> tblFutureStatus { get; set; }
        public virtual DbSet<TblComplaintRequestPhotoDtl> TblComplaintRequestPhotoDtls { get; set; }
        public virtual DbSet<tblCompensationDetailsTypeMaster> tblCompensationDetailsTypeMasters { get; set; }
        public virtual DbSet<tblComplaintCompensationDtl> tblComplaintCompensationDtls { get; set; }
        public virtual DbSet<tblAdminMatrix> tblAdminMatrices { get; set; }
        public virtual DbSet<tblComplaintSettlementDtl> tblComplaintSettlementDtls { get; set; }
        public virtual DbSet<tblComplaintCompensation> tblComplaintCompensations { get; set; }
        public virtual DbSet<TblTemplateMaster> TblTemplateMasters { get; set; }
        public virtual DbSet<tblTSEMaster> tblTSEMasters { get; set; }
        public virtual DbSet<tblProductBatch> tblProductBatches { get; set; }
        public virtual DbSet<tblProductMaster> tblProductMasters { get; set; }
        public virtual DbSet<TblProductManufacturerLocation> TblProductManufacturerLocations { get; set; }
        public virtual DbSet<TblComplaintReapplication> TblComplaintReapplications { get; set; }
        public virtual DbSet<tblComplaintReapplicationInfo> tblComplaintReapplicationInfoes { get; set; }
        public virtual DbSet<tblComplaintQuarantine> tblComplaintQuarantines { get; set; }
        public virtual DbSet<tblComplaintStakeHolder> tblComplaintStakeHolders { get; set; }
        public virtual DbSet<tblComplaintSystemInfoDtl> tblComplaintSystemInfoDtls { get; set; }
        public virtual DbSet<tblComplaintRCA> tblComplaintRCAs { get; set; }
        public virtual DbSet<tblDealerMaster> tblDealerMasters { get; set; }
        public virtual DbSet<tblDepotMaster> tblDepotMasters { get; set; }
        public virtual DbSet<tblFlowMatrix> tblFlowMatrices { get; set; }
        public virtual DbSet<TblComplaintRequestHdr> TblComplaintRequestHdrs { get; set; }
        public virtual DbSet<TblResponse> TblResponses { get; set; }
    
        public virtual ObjectResult<Get_ProductBatchInfo_Result> Get_ProductBatchInfo(Nullable<long> productId)
        {
            var productIdParameter = productId.HasValue ?
                new ObjectParameter("ProductId", productId) :
                new ObjectParameter("ProductId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_ProductBatchInfo_Result>("Get_ProductBatchInfo", productIdParameter);
        }
    
        public virtual ObjectResult<getCategoryList_Result> getCategoryList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCategoryList_Result>("getCategoryList");
        }
    
        public virtual ObjectResult<GetLFGUserDetails_Result> GetLFGUserDetails(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLFGUserDetails_Result>("GetLFGUserDetails", empCodeParameter);
        }
    
        public virtual ObjectResult<getProductList_Result> getProductList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProductList_Result>("getProductList");
        }
    
        public virtual ObjectResult<SP_ComplaintCompensationDtl_Result> SP_ComplaintCompensationDtl(Nullable<int> complaintCompensation_Id)
        {
            var complaintCompensation_IdParameter = complaintCompensation_Id.HasValue ?
                new ObjectParameter("ComplaintCompensation_Id", complaintCompensation_Id) :
                new ObjectParameter("ComplaintCompensation_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ComplaintCompensationDtl_Result>("SP_ComplaintCompensationDtl", complaintCompensation_IdParameter);
        }
    
        public virtual ObjectResult<SP_ComplaintSettlementDtl_Result> SP_ComplaintSettlementDtl(Nullable<int> complaintCompensation_Id)
        {
            var complaintCompensation_IdParameter = complaintCompensation_Id.HasValue ?
                new ObjectParameter("ComplaintCompensation_Id", complaintCompensation_Id) :
                new ObjectParameter("ComplaintCompensation_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_ComplaintSettlementDtl_Result>("SP_ComplaintSettlementDtl", complaintCompensation_IdParameter);
        }
    
        public virtual ObjectResult<Sp_GetALLComplaintRecord_Result> Sp_GetALLComplaintRecord()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetALLComplaintRecord_Result>("Sp_GetALLComplaintRecord");
        }
    
        public virtual ObjectResult<SP_GetApprovedCompRequest_Result> SP_GetApprovedCompRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetApprovedCompRequest_Result>("SP_GetApprovedCompRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetApproveProcessCountRCA_Result> SP_GetApproveProcessCountRCA(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetApproveProcessCountRCA_Result>("SP_GetApproveProcessCountRCA", empCodeParameter);
        }
    
        public virtual ObjectResult<Sp_GetBU_type_Result> Sp_GetBU_type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetBU_type_Result>("Sp_GetBU_type");
        }
    
        public virtual ObjectResult<string> SP_GetBusinessManager()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetBusinessManager");
        }
    
        public virtual ObjectResult<string> SP_GetBusinessManagerForUser(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_GetBusinessManagerForUser", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetCompensationFutureStatusDetails_Result> SP_GetCompensationFutureStatusDetails(Nullable<int> complaintId)
        {
            var complaintIdParameter = complaintId.HasValue ?
                new ObjectParameter("ComplaintId", complaintId) :
                new ObjectParameter("ComplaintId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCompensationFutureStatusDetails_Result>("SP_GetCompensationFutureStatusDetails", complaintIdParameter);
        }
    
        public virtual ObjectResult<SP_GetCompensationRequestStatusDetails_Result> SP_GetCompensationRequestStatusDetails(Nullable<int> complaintId)
        {
            var complaintIdParameter = complaintId.HasValue ?
                new ObjectParameter("ComplaintId", complaintId) :
                new ObjectParameter("ComplaintId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCompensationRequestStatusDetails_Result>("SP_GetCompensationRequestStatusDetails", complaintIdParameter);
        }
    
        public virtual ObjectResult<Sp_GetComplaintDetailForEmail_Result> Sp_GetComplaintDetailForEmail(Nullable<long> complaintId)
        {
            var complaintIdParameter = complaintId.HasValue ?
                new ObjectParameter("ComplaintId", complaintId) :
                new ObjectParameter("ComplaintId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetComplaintDetailForEmail_Result>("Sp_GetComplaintDetailForEmail", complaintIdParameter);
        }
    
        public virtual ObjectResult<SP_GetDealerList_Result> SP_GetDealerList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDealerList_Result>("SP_GetDealerList");
        }
    
        public virtual ObjectResult<SP_GetEmployeeRequestDetails_Result> SP_GetEmployeeRequestDetails(Nullable<int> complaint_Id)
        {
            var complaint_IdParameter = complaint_Id.HasValue ?
                new ObjectParameter("Complaint_Id", complaint_Id) :
                new ObjectParameter("Complaint_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetEmployeeRequestDetails_Result>("SP_GetEmployeeRequestDetails", complaint_IdParameter);
        }
    
        public virtual ObjectResult<SP_GetInProcessCompRequest_Result> SP_GetInProcessCompRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetInProcessCompRequest_Result>("SP_GetInProcessCompRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<Sp_GETName_Result> Sp_GETName(string emp_code)
        {
            var emp_codeParameter = emp_code != null ?
                new ObjectParameter("emp_code", emp_code) :
                new ObjectParameter("emp_code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GETName_Result>("Sp_GETName", emp_codeParameter);
        }
    
        public virtual ObjectResult<SP_GetPendingCompRequest_Result> SP_GetPendingCompRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPendingCompRequest_Result>("SP_GetPendingCompRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetPendingCompRequestForApproval_Result> SP_GetPendingCompRequestForApproval(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPendingCompRequestForApproval_Result>("SP_GetPendingCompRequestForApproval", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetPendingRequest_Result> SP_GetPendingRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPendingRequest_Result>("SP_GetPendingRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetPendingRequestForApproval_Result> SP_GetPendingRequestForApproval(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPendingRequestForApproval_Result>("SP_GetPendingRequestForApproval", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetRejectedCompRequest_Result> SP_GetRejectedCompRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRejectedCompRequest_Result>("SP_GetRejectedCompRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetRequesterDetails_Result> SP_GetRequesterDetails(string emp_Code)
        {
            var emp_CodeParameter = emp_Code != null ?
                new ObjectParameter("Emp_Code", emp_Code) :
                new ObjectParameter("Emp_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRequesterDetails_Result>("SP_GetRequesterDetails", emp_CodeParameter);
        }
    
        public virtual ObjectResult<SP_GetRequestFutureStatusDetails_Result> SP_GetRequestFutureStatusDetails(Nullable<int> complaintId)
        {
            var complaintIdParameter = complaintId.HasValue ?
                new ObjectParameter("ComplaintId", complaintId) :
                new ObjectParameter("ComplaintId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRequestFutureStatusDetails_Result>("SP_GetRequestFutureStatusDetails", complaintIdParameter);
        }
    
        public virtual ObjectResult<SP_GetRequestStatusDetails_Result> SP_GetRequestStatusDetails(Nullable<int> complaintId)
        {
            var complaintIdParameter = complaintId.HasValue ?
                new ObjectParameter("ComplaintId", complaintId) :
                new ObjectParameter("ComplaintId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRequestStatusDetails_Result>("SP_GetRequestStatusDetails", complaintIdParameter);
        }
    
        public virtual ObjectResult<Sp_GetTotalRCACompCount_Result> Sp_GetTotalRCACompCount(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetTotalRCACompCount_Result>("Sp_GetTotalRCACompCount", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetTSE_Result> SP_GetTSE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetTSE_Result>("SP_GetTSE");
        }
    
        public virtual ObjectResult<SP_GetUserClosedRequest_Result> SP_GetUserClosedRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetUserClosedRequest_Result>("SP_GetUserClosedRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_GetUserRejectedRequest_Result> SP_GetUserRejectedRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetUserRejectedRequest_Result>("SP_GetUserRejectedRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TotalApprovedCompRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TotalApprovedCompRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TotalInProcessCompRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TotalInProcessCompRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TotalPendingRequestForApproval(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TotalPendingRequestForApproval", empCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TotalRCARjectCount(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TotalRCARjectCount", empCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_TotalRejectedCompRequest(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_TotalRejectedCompRequest", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_TotalRequestApproved_Result> SP_TotalRequestApproved(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalRequestApproved_Result>("SP_TotalRequestApproved", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_TotalRequestCount_Result> SP_TotalRequestCount(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalRequestCount_Result>("SP_TotalRequestCount", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_TotalRequestInProcess_Result> SP_TotalRequestInProcess(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalRequestInProcess_Result>("SP_TotalRequestInProcess", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_TotalRequestRejected_Result> SP_TotalRequestRejected(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalRequestRejected_Result>("SP_TotalRequestRejected", empCodeParameter);
        }
    
        public virtual ObjectResult<string> SP_ValidateBusinessManager(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_ValidateBusinessManager", empCodeParameter);
        }
    
        public virtual ObjectResult<string> spSelectComplaintType(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spSelectComplaintType", idParameter);
        }
    
        public virtual ObjectResult<SP_GenerateCCReport_Result> SP_GenerateCCReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GenerateCCReport_Result>("SP_GenerateCCReport");
        }
    
        public virtual ObjectResult<SP_TotalRequestApproved_CH_Result> SP_TotalRequestApproved_CH(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalRequestApproved_CH_Result>("SP_TotalRequestApproved_CH", empCodeParameter);
        }
    
        public virtual ObjectResult<SP_TotalRequestApproved_TSE_Result> SP_TotalRequestApproved_TSE(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalRequestApproved_TSE_Result>("SP_TotalRequestApproved_TSE", empCodeParameter);
        }
    
        public virtual ObjectResult<Sp_Manufacturing_productStream_ApprovedComplaint_Result> Sp_Manufacturing_productStream_ApprovedComplaint(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Manufacturing_productStream_ApprovedComplaint_Result>("Sp_Manufacturing_productStream_ApprovedComplaint", empCodeParameter);
        }
    
        public virtual ObjectResult<Sp_Brand_productStream_ApprovedComplaint_Result> Sp_Brand_productStream_ApprovedComplaint(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Brand_productStream_ApprovedComplaint_Result>("Sp_Brand_productStream_ApprovedComplaint", empCodeParameter);
        }
    
        public virtual ObjectResult<Sp_Segment_productStream_ApprovedComplaint_Result> Sp_Segment_productStream_ApprovedComplaint(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Segment_productStream_ApprovedComplaint_Result>("Sp_Segment_productStream_ApprovedComplaint", empCodeParameter);
        }
    
        public virtual ObjectResult<Sp_Get_Responsive_deatil_Result> Sp_Get_Responsive_deatil(string emp_Code)
        {
            var emp_CodeParameter = emp_Code != null ?
                new ObjectParameter("Emp_Code", emp_Code) :
                new ObjectParameter("Emp_Code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_Responsive_deatil_Result>("Sp_Get_Responsive_deatil", emp_CodeParameter);
        }
    
        public virtual ObjectResult<Sp_Get_AllEmp_Details_Result> Sp_Get_AllEmp_Details()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_AllEmp_Details_Result>("Sp_Get_AllEmp_Details");
        }
    
        public virtual ObjectResult<Sp_GetEmployess_Avrg_Response_Result> Sp_GetEmployess_Avrg_Response(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetEmployess_Avrg_Response_Result>("Sp_GetEmployess_Avrg_Response", empCodeParameter);
        }
    
        public virtual ObjectResult<Sp_GetEmployess_Avrg_Response_DETAIL_Result> Sp_GetEmployess_Avrg_Response_DETAIL(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetEmployess_Avrg_Response_DETAIL_Result>("Sp_GetEmployess_Avrg_Response_DETAIL", empCodeParameter);
        }
    
        public virtual ObjectResult<Sp_Get_all_Request_Response_avrg_Result> Sp_Get_all_Request_Response_avrg()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Get_all_Request_Response_avrg_Result>("Sp_Get_all_Request_Response_avrg");
        }
    
        public virtual ObjectResult<GetValidateAccess_Result> GetValidateAccess(string empCode)
        {
            var empCodeParameter = empCode != null ?
                new ObjectParameter("EmpCode", empCode) :
                new ObjectParameter("EmpCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetValidateAccess_Result>("GetValidateAccess", empCodeParameter);
        }
    }
}
