//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblComplaintReapplication
    {
        public long ComplaintHandler_ID { get; set; }
        public Nullable<long> Complaint_ID { get; set; }
        public Nullable<long> Department_ID { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public Nullable<bool> IsQCretainAvailable { get; set; }
        public Nullable<bool> IsQCretailSample { get; set; }
        public bool ProcessReplicated { get; set; }
        public string NonApplicationReason { get; set; }
        public Nullable<System.DateTime> ReApplicationDate { get; set; }
        public Nullable<bool> ReApplicationReqd { get; set; }
        public Nullable<bool> ClosureRecomended { get; set; }
        public string CustomerCommunication { get; set; }
        public Nullable<bool> SystemFollowed { get; set; }
        public string ApplicationComments { get; set; }
        public Nullable<bool> ComplaintObserved { get; set; }
        public Nullable<bool> TMInformed { get; set; }
        public Nullable<bool> TMApproved { get; set; }
        public Nullable<bool> CourseOfAction { get; set; }
        public Nullable<bool> CustomerComplaintClosed { get; set; }
        public Nullable<bool> EvidenceAvailable { get; set; }
        public Nullable<bool> VerifiedInSameBatch { get; set; }
        public Nullable<bool> IsSelf { get; set; }
        public Nullable<bool> SufficientEvidence { get; set; }
        public Nullable<bool> AvailableForFutureEvidence { get; set; }
        public string RemarksForQuetsionaire { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
