//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaintCompensation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblComplaintCompensation()
        {
            this.tblComplaintCompensationDtls = new HashSet<tblComplaintCompensationDtl>();
            this.tblComplaintSettlementDtls = new HashSet<tblComplaintSettlementDtl>();
        }
    
        public int ComplaintCompensation_Id { get; set; }
        public int Department_Id { get; set; }
        public int Complaint_Id { get; set; }
        public int CompensationType { get; set; }
        public Nullable<decimal> CompensationValue { get; set; }
        public string CompensationUnit { get; set; }
        public Nullable<decimal> DamageValue { get; set; }
        public string DamageUnit { get; set; }
        public Nullable<decimal> GoodwillValue { get; set; }
        public string GoodwillUnit { get; set; }
        public Nullable<int> SettlementMode { get; set; }
        public Nullable<decimal> CreditNoteValue { get; set; }
        public string CreditNoteUnit { get; set; }
        public Nullable<decimal> FOCValue { get; set; }
        public Nullable<int> FOCProduct_ID { get; set; }
        public Nullable<int> FOCProductQty { get; set; }
        public string FOCBatchNumber { get; set; }
        public Nullable<decimal> ReplacementValue { get; set; }
        public Nullable<int> ReplacementProduct_ID { get; set; }
        public Nullable<int> ReplacementProductQty { get; set; }
        public string ReplacementProductBatchNumber { get; set; }
        public string SettlementEPNumber { get; set; }
        public Nullable<System.DateTime> MaterialBillingDate { get; set; }
        public Nullable<System.DateTime> CNIssuesDate { get; set; }
        public string Remark { get; set; }
        public string CompensationURL { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComplaintCompensationDtl> tblComplaintCompensationDtls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComplaintSettlementDtl> tblComplaintSettlementDtls { get; set; }
    }
}
