//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblComplaintRequestDtl
    {
        public long ComplaintDtl_ID { get; set; }
        public Nullable<long> Complaint_ID { get; set; }
        public Nullable<long> ComplaintCategory_ID { get; set; }
        public Nullable<long> ComplaintType_ID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblComplaintCategoryMaster tblComplaintCategoryMaster { get; set; }
        public virtual tblComplaintTypeMaster tblComplaintTypeMaster { get; set; }
        public virtual TblComplaintRequestHdr TblComplaintRequestHdr { get; set; }
    }
}
