//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaintSystemInfoDtl
    {
        public long ComplaintSystemInfo_ID { get; set; }
        public Nullable<long> Complaint_ID { get; set; }
        public long Substrate_ID { get; set; }
        public string SubstrateRelated { get; set; }
        public string CoatType_ID { get; set; }
        public string ApplicationType { get; set; }
        public string ApplicationTypeValue { get; set; }
        public string Value3 { get; set; }
        public string Value4 { get; set; }
        public string Value5 { get; set; }
        public string Value6 { get; set; }
        public string Value7 { get; set; }
        public string Value8 { get; set; }
        public string Value9 { get; set; }
        public string Value10 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblSubstrateMaster tblSubstrateMaster { get; set; }
        public virtual TblComplaintRequestHdr TblComplaintRequestHdr { get; set; }
    }
}
