//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaintQuarantine
    {
        public int ComplaintQuartine_Id { get; set; }
        public int Complaint_Id { get; set; }
        public string IsSelected { get; set; }
        public int StockSAPProductVol { get; set; }
        public string StockSAPProductUnit { get; set; }
        public Nullable<int> SysValueProductVol { get; set; }
        public string SysValueProductUnit { get; set; }
        public string AffectedBatchNumbers { get; set; }
        public Nullable<decimal> ExpectedCostOfQuartine { get; set; }
        public string ExpectedCostOfQuartineCurr { get; set; }
        public Nullable<System.DateTime> DateOfExpectedClosure { get; set; }
        public Nullable<bool> StockReceived { get; set; }
        public Nullable<bool> DisposalComplete { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
