//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaintPlantReprocess
    {
        public int ComplaintReprocess_Id { get; set; }
        public int Complaint_Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<bool> StockReceived { get; set; }
        public Nullable<bool> ReproccessingComplete { get; set; }
        public string BatchNumber { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
