//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaintReapplicationInfo
    {
        public long ComplaintManager_ID { get; set; }
        public Nullable<long> Complaint_ID { get; set; }
        public Nullable<long> Department_ID { get; set; }
        public Nullable<bool> IsCompensationRequire { get; set; }
        public Nullable<bool> IsComplaintValid { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
