//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlowMatrix
    {
        public int FlowMatrix_ID { get; set; }
        public string SBU_Name { get; set; }
        public string Plant { get; set; }
        public string OutSourced { get; set; }
        public string Marketing { get; set; }
        public string SCM { get; set; }
        public string R_And_D { get; set; }
        public string BM { get; set; }
        public Nullable<decimal> BMLimit { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> MOdifiedDate { get; set; }
    }
}
