//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblResponse
    {
        public long ResponsiveId { get; set; }
        public long ComplaintId { get; set; }
        public string EmpCode { get; set; }
        public int ResponseTime_InDay { get; set; }
        public System.DateTime ResponseMonth { get; set; }
        public int StatusId { get; set; }
    }
}
