//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCAPPDAL.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTSEMaster
    {
        public long TSE_Id { get; set; }
        public string Area { get; set; }
        public string EmpCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
